### ISSUE TITLE
grunt build command failed

### ISSUE THREAD

**Issue by xiongxoy** [thanpolas/generator-closure#26]
I'm learning Google Closure. The build command of the generated is not working. 
The closurebuilder.py script seems to be deprecated, maybe using the compiler only will resolve this problem?
I'm using OSX 10.9. Thanks!

>> Error: Command failed: app/closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
>> app/closure-library/closure/bin/build/closurebuilder.py: 1666 sources scanned.
>> app/closure-library/closure/bin/build/closurebuilder.py: Building dependency tree..
>> app/closure-library/closure/bin/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
>> is prefererred over using this script for performing JavaScript compilation.
>>
>> Please migrate your codebase.
>>
>> See:
>> https://github.com/google/closure-compiler/wiki/Manage-Closure-Dependencies

>> app/closure-library/closure/goog/base.js:236: ERROR - illegal initialization of @define variable goog.DISALLOW_TEST_ONLY_CODE
>> goog.define('goog.DISALLOW_TEST_ONLY_CODE', COMPILED && !goog.DEBUG);
>>                                             ^
>>
>> 1 error(s), 27 warning(s)
>> Traceback (most recent call last):
>>   File "app/closure-library/closure/bin/build/closurebuilder.py", line 287, in <module>
>>     main()
>>   File "app/closure-library/closure/bin/build/closurebuilder.py", line 276, in main
>>     compiler_flags=options.compiler_flags)
>>   File "/Users/zx/Documents/workspace/js/google-closure/app/closure-library/closure/bin/build/jscompiler.py", line 135, in Compile
>>     raise JsCompilerError('JavaScript compilation failed.')
>> jscompiler.JsCompilerError: JavaScript compilation failed.
>> FAILED to run command for target: app
Warning: Task "closureBuilder:app" failed. Use --force to continue.

Aborted due to warnings.

**Comment by xiongxoy** [comment]
When I comment out the line causing the error, the compilation is successful. 
>goog.define('goog.DISALLOW_TEST_ONLY_CODE', COMPILED && !goog.DEBUG);

**Comment by thanpolas** [comment]
Hi @xiongxoy, I'm sorry, this is rather old code and currently unmaintained.

If you find a way to make it work again then please send a PR and i'll gladly accept it :)

Cheers
